export const someUser = {
    login: 'FatihiZakaria',
    id: 14886248,
    node_id: 'MDQ6VXNlcjE0ODg2MjQ4',
    avatar_url: 'https://avatars.githubusercontent.com/u/14886248?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/FatihiZakaria',
    html_url: 'https://github.com/FatihiZakaria',
    followers_url: 'https://api.github.com/users/FatihiZakaria/followers',
    following_url: 'https://api.github.com/users/FatihiZakaria/following{/other_user}',
    gists_url: 'https://api.github.com/users/FatihiZakaria/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/FatihiZakaria/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/FatihiZakaria/subscriptions',
    organizations_url: 'https://api.github.com/users/FatihiZakaria/orgs',
    repos_url: 'https://api.github.com/users/FatihiZakaria/repos',
    events_url: 'https://api.github.com/users/FatihiZakaria/events{/privacy}',
    received_events_url: 'https://api.github.com/users/FatihiZakaria/received_events',
    type: 'User',
    site_admin: false,
    name: 'Fatihi Zakaria',
    company: null,
    blog: '',
    location: null,
    email: null,
    hireable: null,
    bio: null,
    twitter_username: null,
    public_repos: 5,
    public_gists: 0,
    followers: 0,
    following: 1,
    created_at: '2015-09-29T08:12:02Z',
    updated_at: '2022-04-29T14:30:48Z',
};

export const expectedUserData = {
    name: 'Fatihi Zakaria',
    avatar_url: 'https://avatars.githubusercontent.com/u/14886248?v=4',
};
