export const someRepos = [
    {
        id: 44833593,
        node_id: 'MDEwOlJlcG9zaXRvcnk0NDgzMzU5Mw==',
        name: 'd3pie',
        full_name: 'FatihiZakaria/d3pie',
        private: false,
        owner: {
            login: 'FatihiZakaria',
            id: 14886248,
            node_id: 'MDQ6VXNlcjE0ODg2MjQ4',
            avatar_url: 'https://avatars.githubusercontent.com/u/14886248?v=4',
            gravatar_id: '',
            url: 'https://api.github.com/users/FatihiZakaria',
            html_url: 'https://github.com/FatihiZakaria',
            followers_url: 'https://api.github.com/users/FatihiZakaria/followers',
            following_url: 'https://api.github.com/users/FatihiZakaria/following{/other_user}',
            gists_url: 'https://api.github.com/users/FatihiZakaria/gists{/gist_id}',
            starred_url: 'https://api.github.com/users/FatihiZakaria/starred{/owner}{/repo}',
            subscriptions_url: 'https://api.github.com/users/FatihiZakaria/subscriptions',
            organizations_url: 'https://api.github.com/users/FatihiZakaria/orgs',
            repos_url: 'https://api.github.com/users/FatihiZakaria/repos',
            events_url: 'https://api.github.com/users/FatihiZakaria/events{/privacy}',
            received_events_url: 'https://api.github.com/users/FatihiZakaria/received_events',
            type: 'User',
            site_admin: false,
        },
        html_url: 'https://github.com/FatihiZakaria/d3pie',
        description: 'A configurable pie chart lib and generator built on d3.js',
        fork: true,
        url: 'https://api.github.com/repos/FatihiZakaria/d3pie',
        forks_url: 'https://api.github.com/repos/FatihiZakaria/d3pie/forks',
        keys_url: 'https://api.github.com/repos/FatihiZakaria/d3pie/keys{/key_id}',
        collaborators_url:
            'https://api.github.com/repos/FatihiZakaria/d3pie/collaborators{/collaborator}',
        teams_url: 'https://api.github.com/repos/FatihiZakaria/d3pie/teams',
        hooks_url: 'https://api.github.com/repos/FatihiZakaria/d3pie/hooks',
        issue_events_url: 'https://api.github.com/repos/FatihiZakaria/d3pie/issues/events{/number}',
        events_url: 'https://api.github.com/repos/FatihiZakaria/d3pie/events',
        assignees_url: 'https://api.github.com/repos/FatihiZakaria/d3pie/assignees{/user}',
        branches_url: 'https://api.github.com/repos/FatihiZakaria/d3pie/branches{/branch}',
        tags_url: 'https://api.github.com/repos/FatihiZakaria/d3pie/tags',
        blobs_url: 'https://api.github.com/repos/FatihiZakaria/d3pie/git/blobs{/sha}',
        git_tags_url: 'https://api.github.com/repos/FatihiZakaria/d3pie/git/tags{/sha}',
        git_refs_url: 'https://api.github.com/repos/FatihiZakaria/d3pie/git/refs{/sha}',
        trees_url: 'https://api.github.com/repos/FatihiZakaria/d3pie/git/trees{/sha}',
        statuses_url: 'https://api.github.com/repos/FatihiZakaria/d3pie/statuses/{sha}',
        languages_url: 'https://api.github.com/repos/FatihiZakaria/d3pie/languages',
        stargazers_url: 'https://api.github.com/repos/FatihiZakaria/d3pie/stargazers',
        contributors_url: 'https://api.github.com/repos/FatihiZakaria/d3pie/contributors',
        subscribers_url: 'https://api.github.com/repos/FatihiZakaria/d3pie/subscribers',
        subscription_url: 'https://api.github.com/repos/FatihiZakaria/d3pie/subscription',
        commits_url: 'https://api.github.com/repos/FatihiZakaria/d3pie/commits{/sha}',
        git_commits_url: 'https://api.github.com/repos/FatihiZakaria/d3pie/git/commits{/sha}',
        comments_url: 'https://api.github.com/repos/FatihiZakaria/d3pie/comments{/number}',
        issue_comment_url:
            'https://api.github.com/repos/FatihiZakaria/d3pie/issues/comments{/number}',
        contents_url: 'https://api.github.com/repos/FatihiZakaria/d3pie/contents/{+path}',
        compare_url: 'https://api.github.com/repos/FatihiZakaria/d3pie/compare/{base}...{head}',
        merges_url: 'https://api.github.com/repos/FatihiZakaria/d3pie/merges',
        archive_url: 'https://api.github.com/repos/FatihiZakaria/d3pie/{archive_format}{/ref}',
        downloads_url: 'https://api.github.com/repos/FatihiZakaria/d3pie/downloads',
        issues_url: 'https://api.github.com/repos/FatihiZakaria/d3pie/issues{/number}',
        pulls_url: 'https://api.github.com/repos/FatihiZakaria/d3pie/pulls{/number}',
        milestones_url: 'https://api.github.com/repos/FatihiZakaria/d3pie/milestones{/number}',
        notifications_url:
            'https://api.github.com/repos/FatihiZakaria/d3pie/notifications{?since,all,participating}',
        labels_url: 'https://api.github.com/repos/FatihiZakaria/d3pie/labels{/name}',
        releases_url: 'https://api.github.com/repos/FatihiZakaria/d3pie/releases{/id}',
        deployments_url: 'https://api.github.com/repos/FatihiZakaria/d3pie/deployments',
        created_at: '2015-10-23T19:20:17Z',
        updated_at: '2022-04-30T10:40:46Z',
        pushed_at: '2015-10-07T01:26:19Z',
        git_url: 'git://github.com/FatihiZakaria/d3pie.git',
        ssh_url: 'git@github.com:FatihiZakaria/d3pie.git',
        clone_url: 'https://github.com/FatihiZakaria/d3pie.git',
        svn_url: 'https://github.com/FatihiZakaria/d3pie',
        homepage: 'http://d3pie.org',
        size: 3580,
        stargazers_count: 1,
        watchers_count: 1,
        language: 'JavaScript',
        has_issues: false,
        has_projects: true,
        has_downloads: true,
        has_wiki: true,
        has_pages: false,
        forks_count: 0,
        mirror_url: null,
        archived: false,
        disabled: false,
        open_issues_count: 0,
        license: {
            key: 'mit',
            name: 'MIT License',
            spdx_id: 'MIT',
            url: 'https://api.github.com/licenses/mit',
            node_id: 'MDc6TGljZW5zZTEz',
        },
        allow_forking: true,
        is_template: false,
        topics: [],
        visibility: 'public',
        forks: 0,
        open_issues: 0,
        watchers: 1,
        default_branch: 'master',
    },
    {
        id: 48098683,
        node_id: 'MDEwOlJlcG9zaXRvcnk0ODA5ODY4Mw==',
        name: 'DevoirFatihiZakaria',
        full_name: 'FatihiZakaria/DevoirFatihiZakaria',
        private: false,
        owner: {
            login: 'FatihiZakaria',
            id: 14886248,
            node_id: 'MDQ6VXNlcjE0ODg2MjQ4',
            avatar_url: 'https://avatars.githubusercontent.com/u/14886248?v=4',
            gravatar_id: '',
            url: 'https://api.github.com/users/FatihiZakaria',
            html_url: 'https://github.com/FatihiZakaria',
            followers_url: 'https://api.github.com/users/FatihiZakaria/followers',
            following_url: 'https://api.github.com/users/FatihiZakaria/following{/other_user}',
            gists_url: 'https://api.github.com/users/FatihiZakaria/gists{/gist_id}',
            starred_url: 'https://api.github.com/users/FatihiZakaria/starred{/owner}{/repo}',
            subscriptions_url: 'https://api.github.com/users/FatihiZakaria/subscriptions',
            organizations_url: 'https://api.github.com/users/FatihiZakaria/orgs',
            repos_url: 'https://api.github.com/users/FatihiZakaria/repos',
            events_url: 'https://api.github.com/users/FatihiZakaria/events{/privacy}',
            received_events_url: 'https://api.github.com/users/FatihiZakaria/received_events',
            type: 'User',
            site_admin: false,
        },
        html_url: 'https://github.com/FatihiZakaria/DevoirFatihiZakaria',
        description: null,
        fork: false,
        url: 'https://api.github.com/repos/FatihiZakaria/DevoirFatihiZakaria',
        forks_url: 'https://api.github.com/repos/FatihiZakaria/DevoirFatihiZakaria/forks',
        keys_url: 'https://api.github.com/repos/FatihiZakaria/DevoirFatihiZakaria/keys{/key_id}',
        collaborators_url:
            'https://api.github.com/repos/FatihiZakaria/DevoirFatihiZakaria/collaborators{/collaborator}',
        teams_url: 'https://api.github.com/repos/FatihiZakaria/DevoirFatihiZakaria/teams',
        hooks_url: 'https://api.github.com/repos/FatihiZakaria/DevoirFatihiZakaria/hooks',
        issue_events_url:
            'https://api.github.com/repos/FatihiZakaria/DevoirFatihiZakaria/issues/events{/number}',
        events_url: 'https://api.github.com/repos/FatihiZakaria/DevoirFatihiZakaria/events',
        assignees_url:
            'https://api.github.com/repos/FatihiZakaria/DevoirFatihiZakaria/assignees{/user}',
        branches_url:
            'https://api.github.com/repos/FatihiZakaria/DevoirFatihiZakaria/branches{/branch}',
        tags_url: 'https://api.github.com/repos/FatihiZakaria/DevoirFatihiZakaria/tags',
        blobs_url: 'https://api.github.com/repos/FatihiZakaria/DevoirFatihiZakaria/git/blobs{/sha}',
        git_tags_url:
            'https://api.github.com/repos/FatihiZakaria/DevoirFatihiZakaria/git/tags{/sha}',
        git_refs_url:
            'https://api.github.com/repos/FatihiZakaria/DevoirFatihiZakaria/git/refs{/sha}',
        trees_url: 'https://api.github.com/repos/FatihiZakaria/DevoirFatihiZakaria/git/trees{/sha}',
        statuses_url:
            'https://api.github.com/repos/FatihiZakaria/DevoirFatihiZakaria/statuses/{sha}',
        languages_url: 'https://api.github.com/repos/FatihiZakaria/DevoirFatihiZakaria/languages',
        stargazers_url: 'https://api.github.com/repos/FatihiZakaria/DevoirFatihiZakaria/stargazers',
        contributors_url:
            'https://api.github.com/repos/FatihiZakaria/DevoirFatihiZakaria/contributors',
        subscribers_url:
            'https://api.github.com/repos/FatihiZakaria/DevoirFatihiZakaria/subscribers',
        subscription_url:
            'https://api.github.com/repos/FatihiZakaria/DevoirFatihiZakaria/subscription',
        commits_url: 'https://api.github.com/repos/FatihiZakaria/DevoirFatihiZakaria/commits{/sha}',
        git_commits_url:
            'https://api.github.com/repos/FatihiZakaria/DevoirFatihiZakaria/git/commits{/sha}',
        comments_url:
            'https://api.github.com/repos/FatihiZakaria/DevoirFatihiZakaria/comments{/number}',
        issue_comment_url:
            'https://api.github.com/repos/FatihiZakaria/DevoirFatihiZakaria/issues/comments{/number}',
        contents_url:
            'https://api.github.com/repos/FatihiZakaria/DevoirFatihiZakaria/contents/{+path}',
        compare_url:
            'https://api.github.com/repos/FatihiZakaria/DevoirFatihiZakaria/compare/{base}...{head}',
        merges_url: 'https://api.github.com/repos/FatihiZakaria/DevoirFatihiZakaria/merges',
        archive_url:
            'https://api.github.com/repos/FatihiZakaria/DevoirFatihiZakaria/{archive_format}{/ref}',
        downloads_url: 'https://api.github.com/repos/FatihiZakaria/DevoirFatihiZakaria/downloads',
        issues_url:
            'https://api.github.com/repos/FatihiZakaria/DevoirFatihiZakaria/issues{/number}',
        pulls_url: 'https://api.github.com/repos/FatihiZakaria/DevoirFatihiZakaria/pulls{/number}',
        milestones_url:
            'https://api.github.com/repos/FatihiZakaria/DevoirFatihiZakaria/milestones{/number}',
        notifications_url:
            'https://api.github.com/repos/FatihiZakaria/DevoirFatihiZakaria/notifications{?since,all,participating}',
        labels_url: 'https://api.github.com/repos/FatihiZakaria/DevoirFatihiZakaria/labels{/name}',
        releases_url:
            'https://api.github.com/repos/FatihiZakaria/DevoirFatihiZakaria/releases{/id}',
        deployments_url:
            'https://api.github.com/repos/FatihiZakaria/DevoirFatihiZakaria/deployments',
        created_at: '2015-12-16T08:54:36Z',
        updated_at: '2015-12-16T08:54:36Z',
        pushed_at: '2015-12-16T08:54:36Z',
        git_url: 'git://github.com/FatihiZakaria/DevoirFatihiZakaria.git',
        ssh_url: 'git@github.com:FatihiZakaria/DevoirFatihiZakaria.git',
        clone_url: 'https://github.com/FatihiZakaria/DevoirFatihiZakaria.git',
        svn_url: 'https://github.com/FatihiZakaria/DevoirFatihiZakaria',
        homepage: null,
        size: 0,
        stargazers_count: 0,
        watchers_count: 0,
        language: null,
        has_issues: true,
        has_projects: true,
        has_downloads: true,
        has_wiki: true,
        has_pages: false,
        forks_count: 0,
        mirror_url: null,
        archived: false,
        disabled: false,
        open_issues_count: 0,
        license: null,
        allow_forking: true,
        is_template: false,
        topics: [],
        visibility: 'public',
        forks: 0,
        open_issues: 0,
        watchers: 0,
        default_branch: 'master',
    },
    {
        id: 105476866,
        node_id: 'MDEwOlJlcG9zaXRvcnkxMDU0NzY4NjY=',
        name: 'foodmeup',
        full_name: 'FatihiZakaria/foodmeup',
        private: false,
        owner: {
            login: 'FatihiZakaria',
            id: 14886248,
            node_id: 'MDQ6VXNlcjE0ODg2MjQ4',
            avatar_url: 'https://avatars.githubusercontent.com/u/14886248?v=4',
            gravatar_id: '',
            url: 'https://api.github.com/users/FatihiZakaria',
            html_url: 'https://github.com/FatihiZakaria',
            followers_url: 'https://api.github.com/users/FatihiZakaria/followers',
            following_url: 'https://api.github.com/users/FatihiZakaria/following{/other_user}',
            gists_url: 'https://api.github.com/users/FatihiZakaria/gists{/gist_id}',
            starred_url: 'https://api.github.com/users/FatihiZakaria/starred{/owner}{/repo}',
            subscriptions_url: 'https://api.github.com/users/FatihiZakaria/subscriptions',
            organizations_url: 'https://api.github.com/users/FatihiZakaria/orgs',
            repos_url: 'https://api.github.com/users/FatihiZakaria/repos',
            events_url: 'https://api.github.com/users/FatihiZakaria/events{/privacy}',
            received_events_url: 'https://api.github.com/users/FatihiZakaria/received_events',
            type: 'User',
            site_admin: false,
        },
        html_url: 'https://github.com/FatihiZakaria/foodmeup',
        description: null,
        fork: false,
        url: 'https://api.github.com/repos/FatihiZakaria/foodmeup',
        forks_url: 'https://api.github.com/repos/FatihiZakaria/foodmeup/forks',
        keys_url: 'https://api.github.com/repos/FatihiZakaria/foodmeup/keys{/key_id}',
        collaborators_url:
            'https://api.github.com/repos/FatihiZakaria/foodmeup/collaborators{/collaborator}',
        teams_url: 'https://api.github.com/repos/FatihiZakaria/foodmeup/teams',
        hooks_url: 'https://api.github.com/repos/FatihiZakaria/foodmeup/hooks',
        issue_events_url:
            'https://api.github.com/repos/FatihiZakaria/foodmeup/issues/events{/number}',
        events_url: 'https://api.github.com/repos/FatihiZakaria/foodmeup/events',
        assignees_url: 'https://api.github.com/repos/FatihiZakaria/foodmeup/assignees{/user}',
        branches_url: 'https://api.github.com/repos/FatihiZakaria/foodmeup/branches{/branch}',
        tags_url: 'https://api.github.com/repos/FatihiZakaria/foodmeup/tags',
        blobs_url: 'https://api.github.com/repos/FatihiZakaria/foodmeup/git/blobs{/sha}',
        git_tags_url: 'https://api.github.com/repos/FatihiZakaria/foodmeup/git/tags{/sha}',
        git_refs_url: 'https://api.github.com/repos/FatihiZakaria/foodmeup/git/refs{/sha}',
        trees_url: 'https://api.github.com/repos/FatihiZakaria/foodmeup/git/trees{/sha}',
        statuses_url: 'https://api.github.com/repos/FatihiZakaria/foodmeup/statuses/{sha}',
        languages_url: 'https://api.github.com/repos/FatihiZakaria/foodmeup/languages',
        stargazers_url: 'https://api.github.com/repos/FatihiZakaria/foodmeup/stargazers',
        contributors_url: 'https://api.github.com/repos/FatihiZakaria/foodmeup/contributors',
        subscribers_url: 'https://api.github.com/repos/FatihiZakaria/foodmeup/subscribers',
        subscription_url: 'https://api.github.com/repos/FatihiZakaria/foodmeup/subscription',
        commits_url: 'https://api.github.com/repos/FatihiZakaria/foodmeup/commits{/sha}',
        git_commits_url: 'https://api.github.com/repos/FatihiZakaria/foodmeup/git/commits{/sha}',
        comments_url: 'https://api.github.com/repos/FatihiZakaria/foodmeup/comments{/number}',
        issue_comment_url:
            'https://api.github.com/repos/FatihiZakaria/foodmeup/issues/comments{/number}',
        contents_url: 'https://api.github.com/repos/FatihiZakaria/foodmeup/contents/{+path}',
        compare_url: 'https://api.github.com/repos/FatihiZakaria/foodmeup/compare/{base}...{head}',
        merges_url: 'https://api.github.com/repos/FatihiZakaria/foodmeup/merges',
        archive_url: 'https://api.github.com/repos/FatihiZakaria/foodmeup/{archive_format}{/ref}',
        downloads_url: 'https://api.github.com/repos/FatihiZakaria/foodmeup/downloads',
        issues_url: 'https://api.github.com/repos/FatihiZakaria/foodmeup/issues{/number}',
        pulls_url: 'https://api.github.com/repos/FatihiZakaria/foodmeup/pulls{/number}',
        milestones_url: 'https://api.github.com/repos/FatihiZakaria/foodmeup/milestones{/number}',
        notifications_url:
            'https://api.github.com/repos/FatihiZakaria/foodmeup/notifications{?since,all,participating}',
        labels_url: 'https://api.github.com/repos/FatihiZakaria/foodmeup/labels{/name}',
        releases_url: 'https://api.github.com/repos/FatihiZakaria/foodmeup/releases{/id}',
        deployments_url: 'https://api.github.com/repos/FatihiZakaria/foodmeup/deployments',
        created_at: '2017-10-01T21:47:46Z',
        updated_at: '2022-04-30T10:40:43Z',
        pushed_at: '2017-10-01T21:47:46Z',
        git_url: 'git://github.com/FatihiZakaria/foodmeup.git',
        ssh_url: 'git@github.com:FatihiZakaria/foodmeup.git',
        clone_url: 'https://github.com/FatihiZakaria/foodmeup.git',
        svn_url: 'https://github.com/FatihiZakaria/foodmeup',
        homepage: null,
        size: 0,
        stargazers_count: 1,
        watchers_count: 1,
        language: null,
        has_issues: true,
        has_projects: true,
        has_downloads: true,
        has_wiki: true,
        has_pages: false,
        forks_count: 0,
        mirror_url: null,
        archived: false,
        disabled: false,
        open_issues_count: 0,
        license: null,
        allow_forking: true,
        is_template: false,
        topics: [],
        visibility: 'public',
        forks: 0,
        open_issues: 0,
        watchers: 1,
        default_branch: 'master',
    },
    {
        id: 105477267,
        node_id: 'MDEwOlJlcG9zaXRvcnkxMDU0NzcyNjc=',
        name: 'repository',
        full_name: 'FatihiZakaria/repository',
        private: false,
        owner: {
            login: 'FatihiZakaria',
            id: 14886248,
            node_id: 'MDQ6VXNlcjE0ODg2MjQ4',
            avatar_url: 'https://avatars.githubusercontent.com/u/14886248?v=4',
            gravatar_id: '',
            url: 'https://api.github.com/users/FatihiZakaria',
            html_url: 'https://github.com/FatihiZakaria',
            followers_url: 'https://api.github.com/users/FatihiZakaria/followers',
            following_url: 'https://api.github.com/users/FatihiZakaria/following{/other_user}',
            gists_url: 'https://api.github.com/users/FatihiZakaria/gists{/gist_id}',
            starred_url: 'https://api.github.com/users/FatihiZakaria/starred{/owner}{/repo}',
            subscriptions_url: 'https://api.github.com/users/FatihiZakaria/subscriptions',
            organizations_url: 'https://api.github.com/users/FatihiZakaria/orgs',
            repos_url: 'https://api.github.com/users/FatihiZakaria/repos',
            events_url: 'https://api.github.com/users/FatihiZakaria/events{/privacy}',
            received_events_url: 'https://api.github.com/users/FatihiZakaria/received_events',
            type: 'User',
            site_admin: false,
        },
        html_url: 'https://github.com/FatihiZakaria/repository',
        description: null,
        fork: false,
        url: 'https://api.github.com/repos/FatihiZakaria/repository',
        forks_url: 'https://api.github.com/repos/FatihiZakaria/repository/forks',
        keys_url: 'https://api.github.com/repos/FatihiZakaria/repository/keys{/key_id}',
        collaborators_url:
            'https://api.github.com/repos/FatihiZakaria/repository/collaborators{/collaborator}',
        teams_url: 'https://api.github.com/repos/FatihiZakaria/repository/teams',
        hooks_url: 'https://api.github.com/repos/FatihiZakaria/repository/hooks',
        issue_events_url:
            'https://api.github.com/repos/FatihiZakaria/repository/issues/events{/number}',
        events_url: 'https://api.github.com/repos/FatihiZakaria/repository/events',
        assignees_url: 'https://api.github.com/repos/FatihiZakaria/repository/assignees{/user}',
        branches_url: 'https://api.github.com/repos/FatihiZakaria/repository/branches{/branch}',
        tags_url: 'https://api.github.com/repos/FatihiZakaria/repository/tags',
        blobs_url: 'https://api.github.com/repos/FatihiZakaria/repository/git/blobs{/sha}',
        git_tags_url: 'https://api.github.com/repos/FatihiZakaria/repository/git/tags{/sha}',
        git_refs_url: 'https://api.github.com/repos/FatihiZakaria/repository/git/refs{/sha}',
        trees_url: 'https://api.github.com/repos/FatihiZakaria/repository/git/trees{/sha}',
        statuses_url: 'https://api.github.com/repos/FatihiZakaria/repository/statuses/{sha}',
        languages_url: 'https://api.github.com/repos/FatihiZakaria/repository/languages',
        stargazers_url: 'https://api.github.com/repos/FatihiZakaria/repository/stargazers',
        contributors_url: 'https://api.github.com/repos/FatihiZakaria/repository/contributors',
        subscribers_url: 'https://api.github.com/repos/FatihiZakaria/repository/subscribers',
        subscription_url: 'https://api.github.com/repos/FatihiZakaria/repository/subscription',
        commits_url: 'https://api.github.com/repos/FatihiZakaria/repository/commits{/sha}',
        git_commits_url: 'https://api.github.com/repos/FatihiZakaria/repository/git/commits{/sha}',
        comments_url: 'https://api.github.com/repos/FatihiZakaria/repository/comments{/number}',
        issue_comment_url:
            'https://api.github.com/repos/FatihiZakaria/repository/issues/comments{/number}',
        contents_url: 'https://api.github.com/repos/FatihiZakaria/repository/contents/{+path}',
        compare_url:
            'https://api.github.com/repos/FatihiZakaria/repository/compare/{base}...{head}',
        merges_url: 'https://api.github.com/repos/FatihiZakaria/repository/merges',
        archive_url: 'https://api.github.com/repos/FatihiZakaria/repository/{archive_format}{/ref}',
        downloads_url: 'https://api.github.com/repos/FatihiZakaria/repository/downloads',
        issues_url: 'https://api.github.com/repos/FatihiZakaria/repository/issues{/number}',
        pulls_url: 'https://api.github.com/repos/FatihiZakaria/repository/pulls{/number}',
        milestones_url: 'https://api.github.com/repos/FatihiZakaria/repository/milestones{/number}',
        notifications_url:
            'https://api.github.com/repos/FatihiZakaria/repository/notifications{?since,all,participating}',
        labels_url: 'https://api.github.com/repos/FatihiZakaria/repository/labels{/name}',
        releases_url: 'https://api.github.com/repos/FatihiZakaria/repository/releases{/id}',
        deployments_url: 'https://api.github.com/repos/FatihiZakaria/repository/deployments',
        created_at: '2017-10-01T21:54:33Z',
        updated_at: '2017-10-01T21:54:33Z',
        pushed_at: '2017-10-01T21:54:34Z',
        git_url: 'git://github.com/FatihiZakaria/repository.git',
        ssh_url: 'git@github.com:FatihiZakaria/repository.git',
        clone_url: 'https://github.com/FatihiZakaria/repository.git',
        svn_url: 'https://github.com/FatihiZakaria/repository',
        homepage: null,
        size: 0,
        stargazers_count: 0,
        watchers_count: 0,
        language: null,
        has_issues: true,
        has_projects: true,
        has_downloads: true,
        has_wiki: true,
        has_pages: false,
        forks_count: 0,
        mirror_url: null,
        archived: false,
        disabled: false,
        open_issues_count: 0,
        license: null,
        allow_forking: true,
        is_template: false,
        topics: [],
        visibility: 'public',
        forks: 0,
        open_issues: 0,
        watchers: 0,
        default_branch: 'master',
    },
    {
        id: 44137215,
        node_id: 'MDEwOlJlcG9zaXRvcnk0NDEzNzIxNQ==',
        name: 'TrombinoScope',
        full_name: 'FatihiZakaria/TrombinoScope',
        private: false,
        owner: {
            login: 'FatihiZakaria',
            id: 14886248,
            node_id: 'MDQ6VXNlcjE0ODg2MjQ4',
            avatar_url: 'https://avatars.githubusercontent.com/u/14886248?v=4',
            gravatar_id: '',
            url: 'https://api.github.com/users/FatihiZakaria',
            html_url: 'https://github.com/FatihiZakaria',
            followers_url: 'https://api.github.com/users/FatihiZakaria/followers',
            following_url: 'https://api.github.com/users/FatihiZakaria/following{/other_user}',
            gists_url: 'https://api.github.com/users/FatihiZakaria/gists{/gist_id}',
            starred_url: 'https://api.github.com/users/FatihiZakaria/starred{/owner}{/repo}',
            subscriptions_url: 'https://api.github.com/users/FatihiZakaria/subscriptions',
            organizations_url: 'https://api.github.com/users/FatihiZakaria/orgs',
            repos_url: 'https://api.github.com/users/FatihiZakaria/repos',
            events_url: 'https://api.github.com/users/FatihiZakaria/events{/privacy}',
            received_events_url: 'https://api.github.com/users/FatihiZakaria/received_events',
            type: 'User',
            site_admin: false,
        },
        html_url: 'https://github.com/FatihiZakaria/TrombinoScope',
        description: null,
        fork: false,
        url: 'https://api.github.com/repos/FatihiZakaria/TrombinoScope',
        forks_url: 'https://api.github.com/repos/FatihiZakaria/TrombinoScope/forks',
        keys_url: 'https://api.github.com/repos/FatihiZakaria/TrombinoScope/keys{/key_id}',
        collaborators_url:
            'https://api.github.com/repos/FatihiZakaria/TrombinoScope/collaborators{/collaborator}',
        teams_url: 'https://api.github.com/repos/FatihiZakaria/TrombinoScope/teams',
        hooks_url: 'https://api.github.com/repos/FatihiZakaria/TrombinoScope/hooks',
        issue_events_url:
            'https://api.github.com/repos/FatihiZakaria/TrombinoScope/issues/events{/number}',
        events_url: 'https://api.github.com/repos/FatihiZakaria/TrombinoScope/events',
        assignees_url: 'https://api.github.com/repos/FatihiZakaria/TrombinoScope/assignees{/user}',
        branches_url: 'https://api.github.com/repos/FatihiZakaria/TrombinoScope/branches{/branch}',
        tags_url: 'https://api.github.com/repos/FatihiZakaria/TrombinoScope/tags',
        blobs_url: 'https://api.github.com/repos/FatihiZakaria/TrombinoScope/git/blobs{/sha}',
        git_tags_url: 'https://api.github.com/repos/FatihiZakaria/TrombinoScope/git/tags{/sha}',
        git_refs_url: 'https://api.github.com/repos/FatihiZakaria/TrombinoScope/git/refs{/sha}',
        trees_url: 'https://api.github.com/repos/FatihiZakaria/TrombinoScope/git/trees{/sha}',
        statuses_url: 'https://api.github.com/repos/FatihiZakaria/TrombinoScope/statuses/{sha}',
        languages_url: 'https://api.github.com/repos/FatihiZakaria/TrombinoScope/languages',
        stargazers_url: 'https://api.github.com/repos/FatihiZakaria/TrombinoScope/stargazers',
        contributors_url: 'https://api.github.com/repos/FatihiZakaria/TrombinoScope/contributors',
        subscribers_url: 'https://api.github.com/repos/FatihiZakaria/TrombinoScope/subscribers',
        subscription_url: 'https://api.github.com/repos/FatihiZakaria/TrombinoScope/subscription',
        commits_url: 'https://api.github.com/repos/FatihiZakaria/TrombinoScope/commits{/sha}',
        git_commits_url:
            'https://api.github.com/repos/FatihiZakaria/TrombinoScope/git/commits{/sha}',
        comments_url: 'https://api.github.com/repos/FatihiZakaria/TrombinoScope/comments{/number}',
        issue_comment_url:
            'https://api.github.com/repos/FatihiZakaria/TrombinoScope/issues/comments{/number}',
        contents_url: 'https://api.github.com/repos/FatihiZakaria/TrombinoScope/contents/{+path}',
        compare_url:
            'https://api.github.com/repos/FatihiZakaria/TrombinoScope/compare/{base}...{head}',
        merges_url: 'https://api.github.com/repos/FatihiZakaria/TrombinoScope/merges',
        archive_url:
            'https://api.github.com/repos/FatihiZakaria/TrombinoScope/{archive_format}{/ref}',
        downloads_url: 'https://api.github.com/repos/FatihiZakaria/TrombinoScope/downloads',
        issues_url: 'https://api.github.com/repos/FatihiZakaria/TrombinoScope/issues{/number}',
        pulls_url: 'https://api.github.com/repos/FatihiZakaria/TrombinoScope/pulls{/number}',
        milestones_url:
            'https://api.github.com/repos/FatihiZakaria/TrombinoScope/milestones{/number}',
        notifications_url:
            'https://api.github.com/repos/FatihiZakaria/TrombinoScope/notifications{?since,all,participating}',
        labels_url: 'https://api.github.com/repos/FatihiZakaria/TrombinoScope/labels{/name}',
        releases_url: 'https://api.github.com/repos/FatihiZakaria/TrombinoScope/releases{/id}',
        deployments_url: 'https://api.github.com/repos/FatihiZakaria/TrombinoScope/deployments',
        created_at: '2015-10-12T22:16:53Z',
        updated_at: '2022-04-30T10:40:37Z',
        pushed_at: '2015-10-12T22:16:53Z',
        git_url: 'git://github.com/FatihiZakaria/TrombinoScope.git',
        ssh_url: 'git@github.com:FatihiZakaria/TrombinoScope.git',
        clone_url: 'https://github.com/FatihiZakaria/TrombinoScope.git',
        svn_url: 'https://github.com/FatihiZakaria/TrombinoScope',
        homepage: null,
        size: 0,
        stargazers_count: 1,
        watchers_count: 1,
        language: null,
        has_issues: true,
        has_projects: true,
        has_downloads: true,
        has_wiki: true,
        has_pages: false,
        forks_count: 0,
        mirror_url: null,
        archived: false,
        disabled: false,
        open_issues_count: 0,
        license: null,
        allow_forking: true,
        is_template: false,
        topics: [],
        visibility: 'public',
        forks: 0,
        open_issues: 0,
        watchers: 1,
        default_branch: 'master',
    },
];

export const expectedReposData = [
    {
        id: 44833593,
        name: 'd3pie',
        language: 'JavaScript',
        stargazers_count: 1,
        description: 'A configurable pie chart lib and generator built on d3.js',
        created_at: '2015-10-23',
        updated_at: '2022-04-30',
        html_url: 'https://github.com/FatihiZakaria/d3pie',
    },
    {
        id: 48098683,
        name: 'DevoirFatihiZakaria',
        language: null,
        stargazers_count: 0,
        description: null,
        created_at: '2015-12-16',
        updated_at: '2015-12-16',
        html_url: 'https://github.com/FatihiZakaria/DevoirFatihiZakaria',
    },
    {
        id: 105476866,
        name: 'foodmeup',
        language: null,
        stargazers_count: 1,
        description: null,
        created_at: '2017-10-01',
        updated_at: '2022-04-30',
        html_url: 'https://github.com/FatihiZakaria/foodmeup',
    },
    {
        id: 105477267,
        name: 'repository',
        language: null,
        stargazers_count: 0,
        description: null,
        created_at: '2017-10-01',
        updated_at: '2017-10-01',
        html_url: 'https://github.com/FatihiZakaria/repository',
    },
    {
        id: 44137215,
        name: 'TrombinoScope',
        language: null,
        stargazers_count: 1,
        description: null,
        created_at: '2015-10-12',
        updated_at: '2022-04-30',
        html_url: 'https://github.com/FatihiZakaria/TrombinoScope',
    },
];
